[[redirects]]
from = "/dashboard.html"
to = "/dashboard"
force = true

[[redirects]]
from = "/home"
to = "/"
force = true

[[redirects]]
from = "/login.html"
to = "/login"
force = true

[[redirects]]
from = "/register.html"
to = "/register"
force = true

[[redirects]]
from = "/explore.html"
to = "/explore"
force = true

[[redirects]]
from = "/*"
to = "/not-found.html"
status = 404

